name: vprtutorial
channels:
  - conda-forge
  - tobiasrobotics
dependencies:
  - python=3.9
  - numpy
  - pytorch
  - torchvision
  - patchnetvlad
  - natsort
  - tqdm
  - opencv
  - pillow
  - scikit-learn
  - faiss
  - matplotlib-base
  - tensorflow
  - tensorflow-hub
  - scikit-image
  - ipywidgets
